Add warning boxes for some edge cases
Concordium/concordium-smart-contract-tools pull request #115
Opened 2023-07-31 07:41 UTC by DOBEN

## Purpose

Collection of improvements to give better feedback to user for some edge cases that likely are caused by a users' wrong input.

## Changes

- Add warning box if module references in step 1 and step 2 are not the same. 
- Add warning box if embedded schema indicates an input parameter but no input parameter is provided.
- Add check if inputted module reference has the correct length.

2023-07-31 10:40 UTC, schwartz-concordium requested changes

2023-07-31 10:40 UTC, schwartz-concordium commented on front-end-tools/src/Main.tsx
> +    const [shouldWarnInputPramaterInSchemaIgnored, setShouldWarnInputPramaterInSchemaIgnored] = useState(false);
```suggestion
    const [shouldWarnInputParameterInSchemaIgnored, setShouldWarnInputParameterInSchemaIgnored] = useState(false);
```

2023-07-31 12:48 UTC, abizjak commented on front-end-tools/src/Main.tsx
> +                                        <div>Transaction hash:</div>
Same here I think.

2023-08-01 06:06 UTC, schwartz-concordium approved these changes

2023-08-01 06:09 UTC, merged